"""add epub, source_type, url

Revision ID: 045d563e7600
Revises: add_epub_source_type_url
Create Date: 2026-08-16 11:00:45.565618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045d563e7600'
down_revision: Union[str, None] = 'add_epub_source_type_url'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
